theme: jekyll-theme-hacker

name: work-notes

# Short description (goes below the title; it will also be used in the RSS feed)
description: A list of things to work on.

# Your name, as you want it to appear underneath each post and in the footer
author: Mark
